import { db } from "@workspace/db";
import {
  usersTable,
  groupsTable,
  groupMembershipsTable,
  mealsTable,
  videosTable,
  reactionsTable,
  savesTable,
  commentsTable,
} from "@workspace/db/schema";

async function seed() {
  console.log("Seeding demo data...");

  const existing = await db.select().from(usersTable).limit(1);
  if (existing.length > 0) {
    console.log("Data already exists, skipping seed.");
    process.exit(0);
  }

  const users = await db.insert(usersTable).values([
    {
      displayName: "Maya Chen",
      username: "mayachen",
      email: "maya@example.com",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya",
      bio: "Home cook obsessed with Sichuan flavors and meal prep Sundays. I believe food brings people together.",
      locationText: "San Francisco, CA",
      dietaryPreferences: ["gluten-free"],
      cookingInterests: ["Asian fusion", "Sichuan", "meal prep"],
      role: "user" as const,
    },
    {
      displayName: "Carlos Rivera",
      username: "carlosriv",
      email: "carlos@example.com",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=carlos",
      bio: "Weekend grill master and weekday soup enthusiast. Feeding my family of 5 with real food.",
      locationText: "Austin, TX",
      dietaryPreferences: [],
      cookingInterests: ["BBQ", "Mexican", "soups"],
      role: "user" as const,
    },
    {
      displayName: "Priya Sharma",
      username: "priyacooks",
      email: "priya@example.com",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
      bio: "Plant-based chef and nutrition advocate. Everything I make is vegan and packed with flavor.",
      locationText: "New York, NY",
      dietaryPreferences: ["vegan", "plant-based"],
      cookingInterests: ["Indian", "Mediterranean", "vegan", "nutrition"],
      role: "user" as const,
    },
    {
      displayName: "Tom Nakamura",
      username: "tomnaka",
      email: "tom@example.com",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=tom",
      bio: "Ramen nerd and fermentation hobbyist. Currently perfecting my 36-hour tonkotsu broth.",
      locationText: "Seattle, WA",
      dietaryPreferences: [],
      cookingInterests: ["Japanese", "ramen", "fermentation"],
      role: "user" as const,
    },
    {
      displayName: "Sara Okonkwo",
      username: "saraokonkwo",
      email: "sara@example.com",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=sara",
      bio: "West African food traditions meet modern kitchens. Sharing my grandmother's recipes with the world.",
      locationText: "Atlanta, GA",
      dietaryPreferences: [],
      cookingInterests: ["West African", "Nigerian", "traditional"],
      role: "admin" as const,
    },
  ]).returning();

  console.log(`Inserted ${users.length} users`);

  const groups = await db.insert(groupsTable).values([
    {
      name: "Rivera Family Kitchen",
      slug: "rivera-family",
      description: "Where the Rivera clan shares recipes, weekend cook plans, and debates whether abuela's tamales can be improved (they cannot).",
      coverImageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      visibility: "private" as const,
      createdById: users[1].id,
      tags: ["family", "Mexican", "traditional"],
    },
    {
      name: "Fit Meal Prep Crew",
      slug: "fit-meal-prep",
      description: "High-protein, macro-friendly meals shared weekly. We batch cook on Sundays so weekdays don't derail us.",
      coverImageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
      visibility: "public" as const,
      createdById: users[0].id,
      tags: ["meal-prep", "high-protein", "fitness", "health"],
    },
    {
      name: "Plant-Based & Proud",
      slug: "plant-based-proud",
      description: "A community for plant-based eaters to share stunning vegan meals that prove you don't miss anything.",
      coverImageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      visibility: "public" as const,
      createdById: users[2].id,
      tags: ["vegan", "plant-based", "health", "sustainability"],
    },
    {
      name: "Fermentation Station",
      slug: "fermentation-station",
      description: "Dedicated to the ancient art of fermentation. Kombucha, kimchi, sourdough, miso — if it bubbles, we love it.",
      coverImageUrl: "https://images.unsplash.com/photo-1589311880010-12f9cd94e037?w=800&q=80",
      visibility: "public" as const,
      createdById: users[3].id,
      tags: ["fermentation", "Japanese", "kimchi", "sourdough"],
    },
    {
      name: "Afro Kitchen Collective",
      slug: "afro-kitchen",
      description: "Celebrating the rich food traditions of Africa and the diaspora. Jollof rice debates welcome.",
      coverImageUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&q=80",
      visibility: "public" as const,
      createdById: users[4].id,
      tags: ["African", "Nigerian", "diaspora", "traditional"],
    },
  ]).returning();

  console.log(`Inserted ${groups.length} groups`);

  await db.insert(groupMembershipsTable).values([
    { userId: users[1].id, groupId: groups[0].id, role: "admin" as const },
    { userId: users[0].id, groupId: groups[0].id, role: "member" as const },
    { userId: users[0].id, groupId: groups[1].id, role: "admin" as const },
    { userId: users[1].id, groupId: groups[1].id, role: "member" as const },
    { userId: users[2].id, groupId: groups[1].id, role: "member" as const },
    { userId: users[3].id, groupId: groups[1].id, role: "member" as const },
    { userId: users[2].id, groupId: groups[2].id, role: "admin" as const },
    { userId: users[0].id, groupId: groups[2].id, role: "member" as const },
    { userId: users[4].id, groupId: groups[2].id, role: "member" as const },
    { userId: users[3].id, groupId: groups[3].id, role: "admin" as const },
    { userId: users[0].id, groupId: groups[3].id, role: "member" as const },
    { userId: users[4].id, groupId: groups[4].id, role: "admin" as const },
    { userId: users[2].id, groupId: groups[4].id, role: "member" as const },
    { userId: users[1].id, groupId: groups[4].id, role: "member" as const },
  ]);
  console.log("Inserted memberships");

  const meals = await db.insert(mealsTable).values([
    {
      authorId: users[0].id,
      groupId: groups[1].id,
      title: "Sichuan Mapo Tofu with Brown Rice",
      description: "Silky tofu in a fiery, numbing chili bean sauce with ground turkey instead of pork. 30g protein per serving.",
      mealType: "dinner" as const,
      cuisineTags: ["Sichuan", "Chinese", "Asian"],
      dietaryTags: ["high-protein", "gluten-free"],
      imageUrl: "https://images.unsplash.com/photo-1569058242252-623df8d5e021?w=800&q=80",
      servings: 4,
      shareStatus: "available" as const,
      locationText: "San Francisco, CA",
      ingredientsSummary: "Firm tofu, ground turkey, doubanjiang, Sichuan peppercorns, ginger, garlic, scallions, brown rice",
      instructionsSummary: "Fry aromatics and doubanjiang, add stock, tofu cubes, cook 8 min, finish with Sichuan oil. Serve over rice.",
      likeCount: 47,
      saveCount: 23,
      commentCount: 8,
    },
    {
      authorId: users[1].id,
      groupId: groups[0].id,
      title: "Abuela's Black Bean Soup",
      description: "The recipe that built our family. Slow-cooked black beans with smoked ham hock, served with warm corn tortillas.",
      mealType: "lunch" as const,
      cuisineTags: ["Mexican", "Latin American"],
      dietaryTags: ["comfort food", "family-style"],
      imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
      servings: 8,
      shareStatus: "cooking" as const,
      locationText: "Austin, TX",
      ingredientsSummary: "Dried black beans, smoked ham hock, onion, garlic, cumin, oregano, epazote, lime",
      instructionsSummary: "Soak beans overnight. Slow cook with ham hock 3 hours. Season, finish with lime. Serve with crema and cilantro.",
      likeCount: 89,
      saveCount: 41,
      commentCount: 15,
    },
    {
      authorId: users[2].id,
      groupId: groups[2].id,
      title: "Roasted Cauliflower Shawarma Bowl",
      description: "Whole-spiced cauliflower roasted until caramelized, served on herbed rice with tahini and pickled onions.",
      mealType: "dinner" as const,
      cuisineTags: ["Mediterranean", "Middle Eastern"],
      dietaryTags: ["vegan", "plant-based", "healthy"],
      imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
      servings: 3,
      shareStatus: "available" as const,
      locationText: "New York, NY",
      ingredientsSummary: "Cauliflower, shawarma spice blend, herbed rice, tahini, pickled red onions, parsley, lemon",
      instructionsSummary: "Coat cauliflower in spice blend. Roast 425F 30 min. Assemble bowls with rice, tahini drizzle, pickled onions.",
      likeCount: 62,
      saveCount: 38,
      commentCount: 12,
    },
    {
      authorId: users[3].id,
      groupId: groups[3].id,
      title: "36-Hour Tonkotsu Ramen",
      description: "The real deal. Pork bones simmered into silky cloud-white broth. Topped with chashu, marinated egg, nori, bamboo.",
      mealType: "dinner" as const,
      cuisineTags: ["Japanese", "ramen"],
      dietaryTags: ["comfort food"],
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
      servings: 4,
      shareStatus: "idea" as const,
      locationText: "Seattle, WA",
      ingredientsSummary: "Pork trotters, pork neck bones, chashu pork belly, ramen noodles, soft-boiled eggs, nori, bamboo shoots, scallions",
      instructionsSummary: "Blanch and roast bones. Pressure cook 4 hours or simmer 12. Make tare. Cook noodles fresh. Assemble with toppings.",
      likeCount: 113,
      saveCount: 67,
      commentCount: 21,
    },
    {
      authorId: users[4].id,
      groupId: groups[4].id,
      title: "Party Jollof Rice",
      description: "The smoky, party-style Nigerian jollof everyone fights over. Made with long-grain parboiled rice and the correct amount of tomatoes.",
      mealType: "dinner" as const,
      cuisineTags: ["Nigerian", "West African"],
      dietaryTags: ["gluten-free", "family-style"],
      imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
      servings: 10,
      shareStatus: "available" as const,
      locationText: "Atlanta, GA",
      ingredientsSummary: "Long-grain parboiled rice, plum tomatoes, red peppers, scotch bonnet, chicken stock, bay leaves, thyme, seasoning cubes",
      instructionsSummary: "Blend and cook tomatoes down to paste. Add stock and bring to simmer. Par-cook rice in sauce. Steam-finish on low. Rest 10 min.",
      likeCount: 156,
      saveCount: 84,
      commentCount: 34,
    },
    {
      authorId: users[0].id,
      groupId: groups[1].id,
      title: "5-Ingredient Protein Overnight Oats",
      description: "Batch 5 jars Sunday, eat all week. 35g protein per jar, 10 min hands-on time. Game changer for busy mornings.",
      mealType: "breakfast" as const,
      cuisineTags: ["American"],
      dietaryTags: ["high-protein", "meal-prep", "vegetarian"],
      imageUrl: "https://images.unsplash.com/photo-1481671703460-040cb8a2d909?w=800&q=80",
      servings: 5,
      shareStatus: "finished" as const,
      locationText: "San Francisco, CA",
      ingredientsSummary: "Rolled oats, Greek yogurt, protein powder, chia seeds, almond milk, toppings of choice",
      instructionsSummary: "Mix oats, yogurt, protein, chia in jar. Add milk, stir. Refrigerate overnight. Add fresh fruit before eating.",
      likeCount: 78,
      saveCount: 55,
      commentCount: 19,
    },
    {
      authorId: users[2].id,
      groupId: null,
      title: "Mango Cardamom Chia Pudding",
      description: "Tropical and fragrant. Layers of coconut chia pudding with fresh mango and a cardamom-rose syrup.",
      mealType: "dessert" as const,
      cuisineTags: ["Indian", "fusion"],
      dietaryTags: ["vegan", "plant-based", "gluten-free"],
      imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
      servings: 4,
      shareStatus: "available" as const,
      locationText: "New York, NY",
      ingredientsSummary: "Chia seeds, coconut milk, cardamom, rose water, fresh mango, toasted coconut flakes",
      instructionsSummary: "Mix chia in coconut milk with cardamom. Set overnight. Layer with mango. Drizzle with rose syrup. Top with coconut.",
      likeCount: 43,
      saveCount: 31,
      commentCount: 7,
    },
    {
      authorId: users[1].id,
      groupId: null,
      title: "Smoked Brisket Breakfast Tacos",
      description: "Leftover brisket + eggs + charred tortillas. The breakfast that converts people to Texas food culture.",
      mealType: "breakfast" as const,
      cuisineTags: ["Tex-Mex", "BBQ", "American"],
      dietaryTags: ["high-protein"],
      imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
      servings: 6,
      shareStatus: "cooking" as const,
      locationText: "Austin, TX",
      ingredientsSummary: "Smoked brisket, eggs, flour tortillas, pickled jalapeños, cotija cheese, salsa verde, avocado",
      instructionsSummary: "Warm brisket in skillet. Scramble eggs. Char tortillas. Assemble with all toppings. Serve immediately.",
      likeCount: 94,
      saveCount: 52,
      commentCount: 18,
    },
  ]).returning();

  console.log(`Inserted ${meals.length} meals`);

  const videos = await db.insert(videosTable).values([
    {
      authorId: users[0].id,
      linkedMealId: meals[0].id,
      groupId: groups[1].id,
      title: "How to Bloom Sichuan Peppercorns",
      caption: "The secret to real mapo tofu flavor. 45 seconds of technique that changes everything.",
      thumbnailUrl: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80",
      durationSeconds: 45,
      tags: ["Sichuan", "spices", "technique", "Chinese cooking"],
      likeCount: 234,
      saveCount: 98,
      commentCount: 31,
    },
    {
      authorId: users[3].id,
      linkedMealId: meals[3].id,
      groupId: null,
      title: "Ramen Egg in 6 Minutes",
      caption: "Perfect jammy ramen eggs, repeatable every time. The brine is the key.",
      thumbnailUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
      durationSeconds: 90,
      tags: ["Japanese", "eggs", "ramen", "technique"],
      likeCount: 412,
      saveCount: 187,
      commentCount: 56,
    },
    {
      authorId: users[2].id,
      linkedMealId: null,
      groupId: groups[2].id,
      title: "Tahini Without a Blender",
      caption: "Make smooth, silky tahini using just a food processor and patience. Lasts 3 weeks refrigerated.",
      thumbnailUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      durationSeconds: 120,
      tags: ["vegan", "condiment", "hack", "pantry"],
      likeCount: 189,
      saveCount: 112,
      commentCount: 23,
    },
    {
      authorId: users[4].id,
      linkedMealId: meals[4].id,
      groupId: groups[4].id,
      title: "The Smoky Bottom: Party Jollof Technique",
      caption: "Getting the socarrat on jollof rice is a skill. Here is exactly how to do it without burning.",
      thumbnailUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
      durationSeconds: 180,
      tags: ["Nigerian", "jollof", "technique", "West African"],
      likeCount: 567,
      saveCount: 243,
      commentCount: 89,
    },
    {
      authorId: users[1].id,
      linkedMealId: null,
      groupId: null,
      title: "How to Rest Brisket Properly",
      caption: "Most people cut too early. Here is the right way to rest your brisket for maximum juice retention.",
      thumbnailUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
      durationSeconds: 75,
      tags: ["BBQ", "beef", "technique", "Texas BBQ"],
      likeCount: 321,
      saveCount: 144,
      commentCount: 44,
    },
  ]).returning();

  console.log(`Inserted ${videos.length} videos`);

  await db.insert(reactionsTable).values([
    { userId: users[1].id, targetType: "meal" as const, targetId: meals[0].id, reactionType: "like" as const },
    { userId: users[2].id, targetType: "meal" as const, targetId: meals[0].id, reactionType: "yum" as const },
    { userId: users[0].id, targetType: "meal" as const, targetId: meals[1].id, reactionType: "love" as const },
    { userId: users[3].id, targetType: "meal" as const, targetId: meals[3].id, reactionType: "like" as const },
    { userId: users[0].id, targetType: "video" as const, targetId: videos[1].id, reactionType: "like" as const },
    { userId: users[2].id, targetType: "video" as const, targetId: videos[3].id, reactionType: "yum" as const },
  ]);

  await db.insert(savesTable).values([
    { userId: users[0].id, targetType: "meal" as const, targetId: meals[1].id },
    { userId: users[0].id, targetType: "meal" as const, targetId: meals[3].id },
    { userId: users[0].id, targetType: "video" as const, targetId: videos[1].id },
    { userId: users[0].id, targetType: "video" as const, targetId: videos[3].id },
    { userId: users[1].id, targetType: "meal" as const, targetId: meals[2].id },
    { userId: users[2].id, targetType: "meal" as const, targetId: meals[3].id },
  ]);

  await db.insert(commentsTable).values([
    { userId: users[1].id, targetType: "meal" as const, targetId: meals[0].id, body: "Maya this looks incredible, sending this to the meal prep group chat right now" },
    { userId: users[2].id, targetType: "meal" as const, targetId: meals[0].id, body: "Would this work with tempeh instead of ground turkey?" },
    { userId: users[0].id, targetType: "meal" as const, targetId: meals[0].id, body: "Absolutely! Use crumbled tempeh, fry it extra crispy before adding the sauce" },
    { userId: users[0].id, targetType: "meal" as const, targetId: meals[1].id, body: "This soup is making me emotional. Reminds me of my own grandmother's kitchen" },
    { userId: users[3].id, targetType: "video" as const, targetId: videos[1].id, body: "The brine ratios are perfect. Been making these for 2 years, 100% agree on the timing" },
    { userId: users[0].id, targetType: "video" as const, targetId: videos[3].id, body: "Sara you are a genius. Got the bottom perfect on my first try following this method" },
  ]);

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
