import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import groupsRouter from "./groups";
import mealsRouter from "./meals";
import videosRouter from "./videos";
import feedRouter from "./feed";
import engagementRouter from "./engagement";
import battlesRouter from "./battles";
import onboardingRouter from "./onboarding";
import partnerRouter from "./partner";
import judgeRouter from "./judge";
import eventsRouter from "./events";
import storageRouter from "./storage";
import aiRouter from "./ai";
import notificationsRouter from "./notifications";
import pointsRouter from "./points";
import hacksAdminRouter from "./hacks-admin";
import adminRouter from "./admin";
import linkPreviewRouter from "./link-preview";
import creatorRouter from "./creator";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(eventsRouter);
router.use("/users", usersRouter);
router.use("/groups", groupsRouter);
router.use("/meals", mealsRouter);
router.use("/videos", videosRouter);
router.use("/feed", feedRouter);
router.use(engagementRouter);
router.use("/battles", battlesRouter);
router.use(onboardingRouter);
router.use(partnerRouter);
router.use(judgeRouter);
router.use("/storage", storageRouter);
router.use("/ai", aiRouter);
router.use(notificationsRouter);
router.use(pointsRouter);
router.use(hacksAdminRouter);
router.use(adminRouter);
router.use("/api", linkPreviewRouter);
router.use("/api", creatorRouter);

export default router;
